name: flutter_application_1
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_core_web: ^2.10.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSansCondensed
      fonts:
        - asset: assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSans_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans_Condensed-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans_Condensed-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans_Condensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans_Condensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans_Condensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSans_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans_Condensed-ThinItalic.ttf
          weight: 100
          style: italic
    - family: NotoSansExtraCondensed
      fonts:
        - asset: assets/fonts/NotoSans_ExtraCondensed-Regular.ttf
        - asset: assets/fonts/NotoSans_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans_ExtraCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans_ExtraCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans_ExtraCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans_ExtraCondensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/NotoSans_ExtraCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSans_ExtraCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic